### ISSUE TITLE
Remove `scss/double-slash-comment-empty-line-before`

### ISSUE THREAD

**Issue by andrey-hohlov** [interfacesdev/stylelint-config-scss#3]
```scss
.foo {
  background: black;
  /* bad empty string */
  // TODO: find better oclor
  color: white;
  font-size: 14px;
}
```
